// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class CardsDetail
{
    public int CardDetailId { get; set; }

    public string CardName { get; set; }

    public int Cvv { get; set; }

    public string CardNumber { get; set; }

    public bool IsActive { get; set; }

    public int CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<PaymentsDetail> PaymentsDetails { get; set; } = new List<PaymentsDetail>();
}