// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Address { get; set; }

    public virtual ICollection<CardsDetail> CardsDetails { get; set; } = new List<CardsDetail>();

    public virtual User CustomerNavigation { get; set; }

    public virtual ICollection<CustomersVoucher> CustomersVouchers { get; set; } = new List<CustomersVoucher>();

    public virtual FeedBack FeedBack { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}