// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class CustomersVoucher
{
    public int CustomerId { get; set; }

    public int VoucherId { get; set; }

    public bool IsUsed { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Voucher Voucher { get; set; }
}