// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class FeedBack
{
    public int FeedbackId { get; set; }

    public string Review { get; set; }

    public decimal Rate { get; set; }

    public DateTime Date { get; set; }

    public bool IsActive { get; set; }

    public int ProductId { get; set; }

    public int CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}