// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class Offer
{
    public int OfferId { get; set; }

    public string Description { get; set; }

    public decimal Discount { get; set; }

    public DateTime ExpireDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}