// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string CustomerNote { get; set; }

    public int State { get; set; }

    public DateTime Date { get; set; }

    public bool ShippingState { get; set; }

    public string ShippingAddress { get; set; }

    public decimal TotalPrice { get; set; }

    public bool IsActive { get; set; }

    public string OrderName { get; set; }

    public int CustomerId { get; set; }

    public decimal ShippingFees { get; set; }

    public decimal Voucher { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual ICollection<PaymentsDetail> PaymentsDetails { get; set; } = new List<PaymentsDetail>();
}