// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Description { get; set; }

    public int Stock { get; set; }

    public decimal Rate { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public decimal CostPrice { get; set; }

    public int CategoryId { get; set; }

    public int SellerId { get; set; }

    public string Image { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<FeedBack> FeedBacks { get; set; } = new List<FeedBack>();

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual Seller Seller { get; set; }

    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();
}