// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Admin
{
    [Key]
    [Column("adminID")]
    public int AdminId { get; set; }

    [Column("authorityLevelID")]
    public int AuthorityLevelId { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("Admin")]
    public virtual User AdminNavigation { get; set; }
}