// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

[PrimaryKey("CustomerId", "VoucherId")]
public partial class CustomersVoucher
{
    [Key]
    [Column("customerID")]
    public int CustomerId { get; set; }

    [Key]
    [Column("voucherID")]
    public int VoucherId { get; set; }

    [Column("isUsed")]
    public bool IsUsed { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomersVouchers")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("VoucherId")]
    [InverseProperty("CustomersVouchers")]
    public virtual Voucher Voucher { get; set; }
}