// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class FeedBack
{
    [Key]
    [Column("feedbackID")]
    public int FeedbackId { get; set; }

    [Required]
    [Column("review")]
    [StringLength(255)]
    public string Review { get; set; }

    [Column("rate", TypeName = "decimal(2, 1)")]
    public decimal Rate { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("productID")]
    public int ProductId { get; set; }

    [Column("customerID")]
    public int CustomerId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("FeedBacks")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("FeedBacks")]
    public virtual Product Product { get; set; }
}