// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class FRUITABLESContext : DbContext
{
    public FRUITABLESContext()
    {
    }

    public FRUITABLESContext(DbContextOptions<FRUITABLESContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomersVoucher> CustomersVouchers { get; set; }

    public virtual DbSet<FeedBack> FeedBacks { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Seller> Sellers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Voucher> Vouchers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=FRUITABLES;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK__Admins__1788CC4C56A09165");

            entity.Property(e => e.AdminId).ValueGeneratedNever();

            entity.HasOne(d => d.AdminNavigation).WithOne(p => p.Admin)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Admins_Users");
        });
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__23CAF1D8176FC47D");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory).HasConstraintName("FK_Categories_Categories");
        });
        modelBuilder.Entity<Category>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__CB9A1CFF9C6498F5");

            entity.Property(e => e.CustomerId).ValueGeneratedNever();

            entity.HasOne(d => d.CustomerNavigation).WithOne(p => p.Customer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Customers_Users");
        });

        modelBuilder.Entity<CustomersVoucher>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.VoucherId }).HasName("PK__Customer__3942F3E33AD0C851");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomersVouchers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomersVouchers_Customers");

            entity.HasOne(d => d.Voucher).WithMany(p => p.CustomersVouchers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomersVouchers_Vouchers");
        });

        modelBuilder.Entity<FeedBack>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__FeedBack__2613FD2466EB5584");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Customer).WithMany(p => p.FeedBacks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeedBacks_Customers");

            entity.HasOne(d => d.Product).WithMany(p => p.FeedBacks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeedBacks_Products");
        });
        modelBuilder.Entity<FeedBack>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Item__56A128AA56D03533");

            entity.HasOne(d => d.Order).WithMany(p => p.Items)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Items_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.Items)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Items_Products");
        });
        modelBuilder.Entity<Item>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__4808B9938EFEF697");

            entity.HasOne(d => d.User).WithMany(p => p.Messages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_Users");
        });
        modelBuilder.Entity<Message>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Offer>(entity =>
        {
            entity.HasKey(e => e.OfferId).HasName("PK__Offers__589DEA0033F83D24");

            entity.HasOne(d => d.Seller).WithMany(p => p.Offers).HasConstraintName("fk_constraint_name");
        });

        modelBuilder.Entity<Offer>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__3213E83F338B384E");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Customers");
        });
        modelBuilder.Entity<Order>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__2D10D16AA9D5C8A0");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Categories");

            entity.HasOne(d => d.Seller).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Sellers");

            entity.HasMany(d => d.Offers).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductsOffer",
                    r => r.HasOne<Offer>().WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ProductsOffers_Offers"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ProductsOffers_Products"),
                    j =>
                    {
                        j.HasKey("ProductId", "OfferId").HasName("PK__Products__38990FCA3BF7A6BA");
                        j.ToTable("ProductsOffers");
                        j.IndexerProperty<int>("ProductId").HasColumnName("productID");
                        j.IndexerProperty<int>("OfferId").HasColumnName("offerID");
                    });
        });
        modelBuilder.Entity<Product>().HasQueryFilter(o => o.IsActive == true);

        modelBuilder.Entity<Seller>(entity =>
        {
            entity.HasKey(e => e.SellerId).HasName("PK__Sellers__1788CCAC86F4CA3F");

            entity.Property(e => e.SellerId).ValueGeneratedNever();

            entity.HasOne(d => d.SellerNavigation).WithOne(p => p.Seller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sellers_Users");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C9EDF157C");

            entity.Property(e => e.Image).HasDefaultValue("avatar.jpg");
        });

        modelBuilder.Entity<Voucher>(entity =>
        {
            entity.HasKey(e => e.VoucherId).HasName("PK__Vouchers__F53389E90B073F3A");

            entity.HasOne(d => d.Customer).WithMany(p => p.Vouchers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vouchers_Customers");
        });
        modelBuilder.Entity<Voucher>().HasQueryFilter(o => o.IsActive == true);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}