// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Offer
{
    [Key]
    [Column("offerID")]
    public int OfferId { get; set; }

    [Required]
    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("discount", TypeName = "decimal(5, 1)")]
    public decimal Discount { get; set; }

    [Column("expireDate", TypeName = "datetime")]
    public DateTime ExpireDate { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("sellerId")]
    public int? SellerId { get; set; }

    [ForeignKey("SellerId")]
    [InverseProperty("Offers")]
    public virtual Seller Seller { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("Offers")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}