// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Order
{
    [Key]
    [Column("orderID")]
    public int OrderId { get; set; }

    [Column("state")]
    public int State { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("shippingState")]
    public bool ShippingState { get; set; }

    [Required]
    [Column("shippingAddress")]
    [StringLength(255)]
    public string ShippingAddress { get; set; }

    [Column("totalPrice", TypeName = "decimal(5, 1)")]
    public decimal TotalPrice { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Required]
    [Column("orderName")]
    [StringLength(255)]
    public string OrderName { get; set; }

    [Column("customerID")]
    public int CustomerId { get; set; }

    [Column("shippingFees", TypeName = "decimal(5, 1)")]
    public decimal ShippingFees { get; set; }

    [Column("voucher", TypeName = "decimal(5, 1)")]
    public decimal Voucher { get; set; }

    [Column("sellerID")]
    public int? SellerId { get; set; }

    [Column("paid")]
    public bool? Paid { get; set; }

    [Column("paymentMethod")]
    public bool? PaymentMethod { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Orders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}