// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitablesDAL.Models;

public partial class PaymentsDetail
{
    public int PaymentDetailId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime Date { get; set; }

    public bool IsActive { get; set; }

    public int OrderId { get; set; }

    public int CardId { get; set; }

    public virtual CardsDetail Card { get; set; }

    public virtual Order Order { get; set; }
}