// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Product
{
    [Key]
    [Column("productID")]
    public int ProductId { get; set; }

    [Required]
    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("stock")]
    public int Stock { get; set; }

    [Column("rate", TypeName = "decimal(2, 1)")]
    public decimal Rate { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("price", TypeName = "decimal(5, 1)")]
    public decimal Price { get; set; }

    [Column("costPrice", TypeName = "decimal(5, 1)")]
    public decimal CostPrice { get; set; }

    [Column("categoryID")]
    public int CategoryId { get; set; }

    [Column("sellerID")]
    public int SellerId { get; set; }

    [Required]
    [Column("image")]
    [StringLength(50)]
    public string Image { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<FeedBack> FeedBacks { get; set; } = new List<FeedBack>();

    [InverseProperty("Product")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    [ForeignKey("SellerId")]
    [InverseProperty("Products")]
    public virtual Seller Seller { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Products")]
    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();
}