// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Seller
{
    [Key]
    [Column("sellerID")]
    public int SellerId { get; set; }

    [Required]
    [Column("commercialName")]
    [StringLength(50)]
    public string CommercialName { get; set; }

    [Column("rate", TypeName = "decimal(2, 1)")]
    public decimal Rate { get; set; }

    [Required]
    [Column("address")]
    [StringLength(255)]
    public string Address { get; set; }

    [Column("logo")]
    [StringLength(50)]
    public string Logo { get; set; }

    [InverseProperty("Seller")]
    public virtual ICollection<Offer> Offers { get; set; } = new List<Offer>();

    [InverseProperty("Seller")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [ForeignKey("SellerId")]
    [InverseProperty("Seller")]
    public virtual User SellerNavigation { get; set; }
}