// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class User
{
    [Key]
    [Column("userID")]
    public int UserId { get; set; }

    [Required]
    [Column("firstName")]
    [StringLength(20)]
    public string FirstName { get; set; }

    [Required]
    [Column("lastName")]
    [StringLength(20)]
    public string LastName { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Required]
    [Column("phoneNumber")]
    [StringLength(11)]
    public string PhoneNumber { get; set; }

    [Required]
    [Column("email")]
    [StringLength(30)]
    public string Email { get; set; }

    [Column("password")]
    [StringLength(255)]
    public string Password { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("image")]
    [StringLength(10)]
    public string Image { get; set; }

    [InverseProperty("AdminNavigation")]
    public virtual Admin Admin { get; set; }

    [InverseProperty("CustomerNavigation")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [InverseProperty("SellerNavigation")]
    public virtual Seller Seller { get; set; }
}