// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FruitablesDAL.Models;

public partial class Voucher
{
    [Key]
    [Column("voucherID")]
    public int VoucherId { get; set; }

    [Column("amount", TypeName = "decimal(5, 1)")]
    public decimal Amount { get; set; }

    [Required]
    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("expireDate", TypeName = "datetime")]
    public DateTime ExpireDate { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("customerID")]
    public int CustomerId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Vouchers")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Voucher")]
    public virtual ICollection<CustomersVoucher> CustomersVouchers { get; set; } = new List<CustomersVoucher>();
}